#!/usr/bin/env bash

################################################################################
# Prometheus Stack — Installation Functions (Kind target)
#
# Installs kube-prometheus-stack (Prometheus Operator + Prometheus + Alertmanager)
# via Helm into the monitoring namespace, then configures Alertmanager with a
# webhook receiver pointing to the Causa Backend at:
#   http://causa-backend.<INSTALL_NAMESPACE>.svc.cluster.local:8080/api/v1/alerts
#
# Why this is needed on Kind (but not OpenShift):
#   - OpenShift ships with User Workload Monitoring (Prometheus + Alertmanager built in)
#   - Kind is a bare Kubernetes cluster with no monitoring stack
#   - The PrometheusRule CRD (monitoring.coreos.com/v1) does not exist on Kind
#     until the Prometheus Operator is installed
#
# On OpenShift or any cluster that already has Prometheus + Alertmanager running,
# set INSTALL_TARGET to a non-kind value — the installer skips this step entirely.
#
# Helm chart: prometheus-community/kube-prometheus-stack
# Chart docs: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
################################################################################

# Source guard
if [[ -n "${INSTALL_PROMETHEUS_LIB_LOADED:-}" ]]; then return 0; fi
readonly INSTALL_PROMETHEUS_LIB_LOADED=1

# ---------------------------------------------------------------------------
# Constants (overridable via env vars)
# ---------------------------------------------------------------------------
PROMETHEUS_NAMESPACE="${PROMETHEUS_NAMESPACE:-monitoring}"
PROMETHEUS_RELEASE_NAME="${PROMETHEUS_RELEASE_NAME:-kube-prometheus-stack}"
PROMETHEUS_HELM_REPO="https://prometheus-community.github.io/helm-charts"
PROMETHEUS_HELM_REPO_NAME="prometheus-community"
PROMETHEUS_CHART="${PROMETHEUS_HELM_REPO_NAME}/kube-prometheus-stack"
# Wait up to 5 minutes for Prometheus Operator + Alertmanager to be ready
PROMETHEUS_DEPLOY_TIMEOUT="${PROMETHEUS_DEPLOY_TIMEOUT:-300}"

export PROMETHEUS_NAMESPACE PROMETHEUS_RELEASE_NAME

################################################################################
# _causa_alertmanager_webhook_url
# The webhook URL Alertmanager will POST alerts to.
# Uses internal cluster DNS — Alertmanager and Causa Backend are both in-cluster.
################################################################################
_causa_alertmanager_webhook_url() {
    echo "http://causa-backend.${INSTALL_NAMESPACE}.svc.cluster.local:8080/api/v1/alerts"
}

################################################################################
# _prometheus_already_installed
# Returns 0 if the Helm release is already present in PROMETHEUS_NAMESPACE.
################################################################################
_prometheus_already_installed() {
    helm status "${PROMETHEUS_RELEASE_NAME}" \
        --namespace "${PROMETHEUS_NAMESPACE}" &>/dev/null
}

################################################################################
# _write_alertmanager_values
# Writes a temporary Helm values file that:
#   1. Configures a single Alertmanager route → causa-webhook receiver
#   2. Sets the webhook URL to the Causa Backend /api/v1/alerts endpoint
#   3. Disables the default null receiver so all alerts go to Causa
#   4. Keeps Prometheus resource limits low for a local Kind cluster
# Prints the path to the temp file.
################################################################################
_write_alertmanager_values() {
    local values_file; values_file=$(mktemp /tmp/causa-prometheus-values-XXXXXX.yaml) || {
        log_error "mktemp failed for /tmp/causa-prometheus-values-XXXXXX.yaml"
        return 1
    }
    local webhook_url; webhook_url=$(_causa_alertmanager_webhook_url)

    cat > "${values_file}" << YAML
# kube-prometheus-stack values for Causa RCA demo (Kind cluster)
# Generated by install_prometheus.sh — do not edit manually

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      # Send all alerts to the causa-webhook receiver by default
      receiver: causa-webhook
      # Group by pod so each affected pod fires its alert independently
      # rather than batching all pods in the namespace into one notification.
      group_by: ['namespace', 'alertname', 'pod']
      group_wait: 10s
      group_interval: 1m
      # 15m matches the Causa Backend cooldown period — ensures the same alert
      # is not re-sent before a previous RCA has had time to complete.
      repeat_interval: 15m
    receivers:
      - name: causa-webhook
        webhook_configs:
          - url: "${webhook_url}"
            send_resolved: true
            # Pass the full alert payload so Causa can extract
            # workload_name, namespace, and alert details
            http_config: {}
      # Keep null receiver so Alertmanager doesn't complain
      - name: "null"
  alertmanagerSpec:
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"

prometheus:
  prometheusSpec:
    # Pick up PrometheusRule resources from all namespaces
    ruleNamespaceSelector: {}
    ruleSelector: {}
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    # Retention: keep 24h of data (demo only)
    retention: 24h
    retentionSize: "2GB"

# Reduce footprint on Kind — disable components not needed for the demo
grafana:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: false
prometheusOperator:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
YAML

    echo "${values_file}"
}

################################################################################
# install_prometheus
# Main entry point: add Helm repo → install chart → apply PrometheusRule
################################################################################
install_prometheus() {
    log_section_silent "Installing Prometheus Stack"

    if [[ "${DRY_RUN}" == "true" ]]; then
        write_to_log_file "INFO" "Dry run — skipping Prometheus installation"
        return 0
    fi

    # ── 1. Check helm is available ───────────────────────────────────────────
    if ! check_command_exists helm; then
        log_error "helm not found. Install helm first: https://helm.sh/docs/intro/install/"
        return 1
    fi
    write_to_log_file "INFO" "helm found: $(helm version --short 2>/dev/null || echo 'unknown')"

    # ── 2. Add / update Prometheus community Helm repo ───────────────────────
    write_to_log_file "INFO" "Adding Helm repo: ${PROMETHEUS_HELM_REPO_NAME}"
    if ! helm repo add "${PROMETHEUS_HELM_REPO_NAME}" "${PROMETHEUS_HELM_REPO}" \
            >>"${LOG_FILE}" 2>&1; then
        # repo add fails if already added — that is fine
        write_to_log_file "INFO" "Helm repo already present (or add failed — continuing)"
    fi

    if ! helm repo update "${PROMETHEUS_HELM_REPO_NAME}" >>"${LOG_FILE}" 2>&1; then
        write_to_log_file "WARN" "helm repo update failed — using cached chart index"
    fi
    write_to_log_file "SUCCESS" "Helm repo ready: ${PROMETHEUS_HELM_REPO_NAME}"

    # ── 3. Create monitoring namespace ───────────────────────────────────────
    if ! ${KUBE_CLI} get namespace "${PROMETHEUS_NAMESPACE}" &>/dev/null; then
        ${KUBE_CLI} create namespace "${PROMETHEUS_NAMESPACE}" \
            >>"${LOG_FILE}" 2>&1 || true
        write_to_log_file "INFO" "Namespace created: ${PROMETHEUS_NAMESPACE}"
    else
        write_to_log_file "INFO" "Namespace already exists: ${PROMETHEUS_NAMESPACE}"
    fi

    # ── 4. Install or upgrade kube-prometheus-stack ──────────────────────────
    local values_file; values_file=$(_write_alertmanager_values) || {
        log_error "Failed to write Alertmanager values file — aborting Prometheus install"
        return 1
    }
    write_to_log_file "INFO" "Alertmanager webhook URL: $(_causa_alertmanager_webhook_url)"

    if _prometheus_already_installed; then
        write_to_log_file "INFO" "kube-prometheus-stack already installed — upgrading"
        if ! helm upgrade "${PROMETHEUS_RELEASE_NAME}" "${PROMETHEUS_CHART}" \
                --namespace "${PROMETHEUS_NAMESPACE}" \
                --values "${values_file}" \
                --wait \
                --timeout "${PROMETHEUS_DEPLOY_TIMEOUT}s" \
                >>"${LOG_FILE}" 2>&1; then
            rm -f "${values_file}"
            log_error "helm upgrade failed for kube-prometheus-stack"
            return 1
        fi
    else
        write_to_log_file "INFO" "Installing kube-prometheus-stack (this takes ~2 minutes)..."
        if ! helm install "${PROMETHEUS_RELEASE_NAME}" "${PROMETHEUS_CHART}" \
                --namespace "${PROMETHEUS_NAMESPACE}" \
                --values "${values_file}" \
                --wait \
                --timeout "${PROMETHEUS_DEPLOY_TIMEOUT}s" \
                >>"${LOG_FILE}" 2>&1; then
            rm -f "${values_file}"
            log_error "helm install failed for kube-prometheus-stack"
            log_error "Check log for details: ${LOG_FILE}"
            log_error "Manual retry: helm install ${PROMETHEUS_RELEASE_NAME} ${PROMETHEUS_CHART} --namespace ${PROMETHEUS_NAMESPACE}"
            return 1
        fi
    fi

    rm -f "${values_file}"
    write_to_log_file "SUCCESS" "kube-prometheus-stack installed in namespace: ${PROMETHEUS_NAMESPACE}"

    # ── 5. Wait for Prometheus Operator CRD to be registered ─────────────────
    write_to_log_file "INFO" "Waiting for PrometheusRule CRD to be available..."
    local waited=0
    while ! ${KUBE_CLI} get crd prometheusrules.monitoring.coreos.com \
            &>/dev/null; do
        if [[ ${waited} -ge 60 ]]; then
            log_error "Timed out waiting for PrometheusRule CRD"
            return 1
        fi
        sleep 5; waited=$(( waited + 5 ))
    done
    write_to_log_file "SUCCESS" "PrometheusRule CRD is registered"

    # ── 6. Ensure target namespace exists before applying PrometheusRule ──────
    if ! ${KUBE_CLI} get namespace "${INSTALL_NAMESPACE}" &>/dev/null; then
        write_to_log_file "INFO" "Creating namespace: ${INSTALL_NAMESPACE}"
        ${KUBE_CLI} create namespace "${INSTALL_NAMESPACE}" \
            >>"${LOG_FILE}" 2>&1 || true
        write_to_log_file "SUCCESS" "Namespace created: ${INSTALL_NAMESPACE}"
    else
        write_to_log_file "INFO" "Namespace already exists: ${INSTALL_NAMESPACE}"
    fi

    # ── 7. Apply PrometheusRule and NetworkPolicy ─────────────────────────────
    local prom_dir="${SCRIPT_DIR}/manifests/prometheus"
    for manifest in "${prom_dir}/prometheusrule.yaml" "${prom_dir}/networkpolicy.yaml"; do
        if [[ -f "${manifest}" ]]; then
            write_to_log_file "INFO" "Applying manifest: ${manifest}"
            local tmp; tmp=$(mktemp /tmp/causa-prom-manifest-XXXXXX.yaml)
            sed "s/PLACEHOLDER_NAMESPACE/${INSTALL_NAMESPACE}/g" "${manifest}" > "${tmp}"
            if ! ${KUBE_CLI} apply -f "${tmp}" >>"${LOG_FILE}" 2>&1; then
                rm -f "${tmp}"
                log_error "Failed to apply ${manifest}"
                return 1
            fi
            rm -f "${tmp}"
            write_to_log_file "SUCCESS" "Applied: $(basename "${manifest}") to namespace: ${INSTALL_NAMESPACE}"
        else
            write_to_log_file "WARN" "Manifest not found: ${manifest} — skipping"
        fi
    done

    write_to_log_file "SUCCESS" "Prometheus stack installed"
    write_to_log_file "INFO"    "Alertmanager webhook → $(_causa_alertmanager_webhook_url)"
    write_to_log_file "INFO"    "Prometheus UI:    kubectl port-forward -n ${PROMETHEUS_NAMESPACE} svc/kube-prometheus-stack-prometheus 9090:9090"
    write_to_log_file "INFO"    "Alertmanager UI:  kubectl port-forward -n ${PROMETHEUS_NAMESPACE} svc/kube-prometheus-stack-alertmanager 9093:9093"
    return 0
}

################################################################################
# uninstall_prometheus
# Removes the Helm release and deletes the monitoring namespace.
################################################################################
uninstall_prometheus() {
    log_section_silent "Uninstalling Prometheus Stack"

    if [[ "${DRY_RUN}" == "true" ]]; then
        write_to_log_file "INFO" "Dry run — skipping Prometheus uninstall"
        return 0
    fi

    # Guard: if the cluster API is unreachable (e.g. Kind cluster is not running),
    # skip all kubectl/helm operations — there is nothing to delete in a stopped cluster.
    if ! ${KUBE_CLI} cluster-info --request-timeout=5s &>/dev/null; then
        write_to_log_file "WARN" "Cluster API is unreachable — skipping Prometheus uninstall (cluster not running)"
        return 0
    fi

    if ! check_command_exists helm; then
        write_to_log_file "WARN" "helm not found — skipping Prometheus uninstall"
        return 0
    fi

    if _prometheus_already_installed; then
        write_to_log_file "INFO" "Uninstalling Helm release: ${PROMETHEUS_RELEASE_NAME}"
        helm uninstall "${PROMETHEUS_RELEASE_NAME}" \
            --namespace "${PROMETHEUS_NAMESPACE}" \
            >>"${LOG_FILE}" 2>&1 || true
        write_to_log_file "SUCCESS" "kube-prometheus-stack Helm release removed"
    else
        write_to_log_file "INFO" "kube-prometheus-stack not installed — nothing to remove"
    fi

    # Remove PrometheusRule and NetworkPolicy from the install namespace
    local prom_dir="${SCRIPT_DIR}/manifests/prometheus"
    for manifest in "${prom_dir}/prometheusrule.yaml" "${prom_dir}/networkpolicy.yaml"; do
        if [[ -f "${manifest}" ]]; then
            local tmp; tmp=$(mktemp /tmp/causa-prom-manifest-XXXXXX.yaml)
            sed "s/PLACEHOLDER_NAMESPACE/${INSTALL_NAMESPACE}/g" "${manifest}" > "${tmp}"
            ${KUBE_CLI} delete -f "${tmp}" --ignore-not-found=true >>"${LOG_FILE}" 2>&1 || true
            rm -f "${tmp}"
        fi
    done

    # Delete the monitoring namespace (removes all Prometheus/Alertmanager pods)
    if ${KUBE_CLI} get namespace "${PROMETHEUS_NAMESPACE}" &>/dev/null; then
        write_to_log_file "INFO" "Deleting namespace: ${PROMETHEUS_NAMESPACE}"
        ${KUBE_CLI} delete namespace "${PROMETHEUS_NAMESPACE}" \
            >>"${LOG_FILE}" 2>&1 || true
        write_to_log_file "SUCCESS" "Namespace ${PROMETHEUS_NAMESPACE} deleted"
    fi

    # Remove CRDs installed by Prometheus Operator
    write_to_log_file "INFO" "Removing Prometheus Operator CRDs..."
    for crd in \
        alertmanagerconfigs.monitoring.coreos.com \
        alertmanagers.monitoring.coreos.com \
        podmonitors.monitoring.coreos.com \
        probes.monitoring.coreos.com \
        prometheusagents.monitoring.coreos.com \
        prometheuses.monitoring.coreos.com \
        prometheusrules.monitoring.coreos.com \
        scrapeconfigs.monitoring.coreos.com \
        servicemonitors.monitoring.coreos.com \
        thanosrulers.monitoring.coreos.com; do
        ${KUBE_CLI} delete crd "${crd}" --ignore-not-found=true \
            >>"${LOG_FILE}" 2>&1 || true
    done
    write_to_log_file "SUCCESS" "Prometheus Operator CRDs removed"

    write_to_log_file "SUCCESS" "Prometheus stack uninstalled"
    return 0
}

export -f _causa_alertmanager_webhook_url
export -f _write_alertmanager_values
export -f install_prometheus
export -f uninstall_prometheus
